export const skills = [
  "JavaScript",
  "TypeScript",
  "React",
  "Node.js",
  "Python",
  "Django",
  "GraphQL",
  "Docker",
  "Kubernetes",
  "AWS",
  "CI/CD",
  "Agile Methodologies",
  "Unit Testing",
  "RESTful APIs",
  "Microservices",
  "SQL",
  "NoSQL",
  "Git",
  "Webpack",
  "Babel",
  "HTML5",
  "CSS3",
  "Sass",
  "Tailwind CSS",
  "Redux",
  "MobX",
  "Next.js",
  "Gatsby",
  "Jest",
  "Cypress",
  "ESLint",
  "Prettier",
  "Java",
  "Spring Boot",
  "Hibernate",
  "C#",
  ".NET",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Flutter",
  "Dart",
  "Machine Learning",
  "Data Science",
  "DevOps",
  "UI/UX Design",
  "Figma",
  "Adobe XD",
  "React Native",
  "Redux Toolkit",
  "Redis",
  "RabbitMQ",
  "Apache Kafka",
  "ZooKeeper",
  "Prometheus",
  "Loki",
  "Grafana",
  "BullMQ",
  "TypeORM",
  "Sequelize",
  "Prisma",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "MariaDB",
  "Firebase",
  "Supabase",
  "Heroku",
  "Netlify",
  "Vercel",
  "Azure",
  "Google Cloud Platform",
  "DigitalOcean",
  "Linode",
  "Terraform",
  "Ansible",
  "Jenkins",
  "CircleCI",
  "Travis CI",
  "GitHub Actions",
  "Bitbucket Pipelines",
  "Selenium",
  "Puppeteer",
  "Playwright",
  "Cucumber",
  "jasmine",
  "Mocha",
  "Chai",
  "Angular",
  "Vue.js",
  "Svelte",
  "python",
  "FastAPI",
  "Flask",
  "Express.js",
  "NestJS",
  "Hadoop",
  "Spark",
  "Tableau",
  "Power BI",
  "Looker",
  "Sails.js",
  "Backbone.js",
  "Ember.js",
  "Three.js",
  "D3.js",
  "Leaflet.js",
  "Alpine.js",
  "Stimulus.js",
  "Solid.js",
  "Litelement.js",
  "Solr search",
  "Elasticsearch",
  "Logstash",
  "Kibana",
  "Jira",
  "Confluence",
  "Slack",
  "Microsoft Teams",
  "Zoom",
  "Google Meet",
  "Trello",
  "Asana",
  "Notion",
  "Airtable",
  "DataDog",
  "New Relic",
  "Sentry",
  "Rollbar",
  "BugSnag",
  "Honeybadger",
  "Raygun",
  "Postman",
  "Insomnia",
  "AWS Lambda",
  "Google Cloud Functions",
  "Azure Functions",
  "Firebase Functions",
  "AWS S3",
  "Google Cloud Storage",
  "Azure Blob Storage",
  "Cloudflare Workers",
  "Vite",
  "ESBuild",
  "Snowpack",
  "Parcel",
] as const;

export const API_ENDPOINTS = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
};

